import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import styled from 'styled-components';
import Navbar from '@/components/navbar';
import ResetStyles from '@/styles/globals';

export default function Home() {
	return (
		<>
			<Head>
				<title>IDST Projects</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
      <ResetStyles />
			<main>
				<Navbar />
			</main>
		</>
	);
}

